Android (Unity exported): com.unity3d.player.MyBluetoothService.ConnectedThread Class Reference
com.unity3d.player.MyBluetoothService.ConnectedThread Class Reference
Thread that manages a Bluetooth connection.
Public Member Functions
ConnectedThread (BluetoothSocket socket)
Constructor for the ConnectedThread class.
void run ()
Main code that runs in the Thread.
void write (byte[] bytes)
Sends data to the remote device.
void cancel ()
Closes the socket.
Private Attributes
final BluetoothSocket mmSocket
final InputStream mmInStream
final OutputStream mmOutStream
Detailed Description
Thread that manages a Bluetooth connection.
A thread is a thread of execution in a program. The Java Virtual Machine allows an application to have multiple threads of execution running concurrently.
This one manages a BluetoothSocket
Definition at line 235 of file MyBluetoothService.java.
Constructor & Destructor Documentation
ConnectedThread()
com.unity3d.player.MyBluetoothService.ConnectedThread.ConnectedThread (BluetoothSocket socket)
Constructor for the ConnectedThread class.
Parameters
socket RFCOMM Bluetooth Socket object
Manages a RFCOMM Bluetooth Socket
Definition at line 255 of file MyBluetoothService.java.
{
             Log.d(TAG, "ConnectedThread: Starting.");
             mmSocket = socket;
             // Temporary storage for  an input stream for reading bytes from this socket//
             InputStream tmpIn = null;
             // Temporary storage for  an output stream for writing bytes from this socket//
             OutputStream tmpOut = null;
             // dismiss the progressDialog when connection is established //
             try {
                 mProgressDialog.dismiss();
             } catch (NullPointerException e) {
                 e.printStackTrace();
             }
             // Get the InputStream and OutputStream that handle transmissions through the socket using getInputStream() and getOutputStream(), respectively. //
             try {
                 tmpIn = mmSocket.getInputStream();
                 tmpOut = mmSocket.getOutputStream();
             } catch (IOException e) {
                 e.printStackTrace();
             }
             mmInStream = tmpIn;
             mmOutStream = tmpOut;
         }
References com.unity3d.player.MyBluetoothService.ConnectedThread.mmInStream, com.unity3d.player.MyBluetoothService.ConnectedThread.mmOutStream, com.unity3d.player.MyBluetoothService.ConnectedThread.mmSocket, com.unity3d.player.MyBluetoothService.mProgressDialog, and com.unity3d.player.MyBluetoothService.TAG.
Member Function Documentation
cancel()
void com.unity3d.player.MyBluetoothService.ConnectedThread.cancel ()
Closes the socket.
Closes the client socket and causes the thread to finish. Called from the main activity to shut down the connection.
Definition at line 348 of file MyBluetoothService.java.
{
             try {
                 mmSocket.close();
             } catch (IOException e) { }
         }
References com.unity3d.player.MyBluetoothService.ConnectedThread.mmSocket.
Referenced by com.unity3d.player.MyBluetoothService.cancelThreads().
run()
void com.unity3d.player.MyBluetoothService.ConnectedThread.run ()
Main code that runs in the Thread.
Try Catch to read data being sent through the connection with the remote device.
Definition at line 289 of file MyBluetoothService.java.
{
             // buffer store for the stream //
             byte[] buffer = new byte[1024];
             // String buffer to hold incoming data //
             String concatenatedString = "";
             // bytes returned from read() //
             int bytes;
             // Keep listening to the InputStream until an exception occurs //
             while (true) {
                 // Read from the InputStream //
                 try {
                     bytes = mmInStream.read(buffer);
                     String incomingMessage = new String(buffer, 0, bytes);
                     Log.d(TAG, "InputStream: " + incomingMessage);
                     concatenatedString = concatenatedString + incomingMessage;
                     if (incomingMessage.contains("#")) {
                         // send the String till # to be broken up //
                         String[] messagePieces = breakUpString(concatenatedString.substring(0, concatenatedString.indexOf("#")));
                         Log.d(TAG, concatenatedString.substring(0, concatenatedString.indexOf("#")));
                         // empty the concatenatedString //
                         concatenatedString = "";
                         // send it to be processed //
                         Log.d(TAG, messagePieces[0]);
                         messageProcessorFunction(messagePieces);
                     }
                 } catch (IOException e) {
                     Log.e(TAG, "write: Error reading Input Stream. " + e.getMessage() );
                     break;
                 }
             }
         }
References com.unity3d.player.MyBluetoothService.breakUpString(), com.unity3d.player.MyBluetoothService.messageProcessorFunction(), com.unity3d.player.MyBluetoothService.ConnectedThread.mmInStream, and com.unity3d.player.MyBluetoothService.TAG.
write()
void com.unity3d.player.MyBluetoothService.ConnectedThread.write (byte[] bytes)
Sends data to the remote device.
Parameters
bytes Array of bytes to be sent to the remote Bluetooth device
Called this from the main activity to send data to the remote device
Definition at line 334 of file MyBluetoothService.java.
{
             String text = new String(bytes, Charset.defaultCharset());
             Log.d(TAG, "write: Writing to output stream: " + text);
             try {
                 mmOutStream.write(bytes);
             } catch (IOException e) {
                 Log.e(TAG, "write: Error writing to output stream. " + e.getMessage() );
             }
         }
References com.unity3d.player.MyBluetoothService.ConnectedThread.mmOutStream, and com.unity3d.player.MyBluetoothService.TAG.
Referenced by com.unity3d.player.MyBluetoothService.write().
Member Data Documentation
mmInStream
com.unity3d.player.MyBluetoothService.ConnectedThread.mmInStream private
Holds a reference to an InputStream object, one of two types of streams. One that you can read data from
Definition at line 247 of file MyBluetoothService.java.
Referenced by com.unity3d.player.MyBluetoothService.ConnectedThread.ConnectedThread(), and com.unity3d.player.MyBluetoothService.ConnectedThread.run().
mmOutStream
com.unity3d.player.MyBluetoothService.ConnectedThread.mmOutStream private
Holds a reference to an OutputStream object, one of two types of streams. One that you can either write data to
Definition at line 248 of file MyBluetoothService.java.
Referenced by com.unity3d.player.MyBluetoothService.ConnectedThread.ConnectedThread(), and com.unity3d.player.MyBluetoothService.ConnectedThread.write().
mmSocket
final BluetoothSocket com.unity3d.player.MyBluetoothService.ConnectedThread.mmSocket private
Holds the RFCOMM Socket object
Definition at line 239 of file MyBluetoothService.java.
Referenced by com.unity3d.player.MyBluetoothService.ConnectedThread.cancel(), and com.unity3d.player.MyBluetoothService.ConnectedThread.ConnectedThread().
The documentation for this class was generated from the following file:
MyBluetoothService.java